name: Deploy Fullstack to ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  ECR_FRONTEND_REPO: rca-frontend
  ECR_BACKEND_REPO: rca-backend
  ECS_CLUSTER: rca-prod-cluster
  ECS_SERVICE_FRONTEND: frontend-services
  ECS_SERVICE_BACKEND: backend-services
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Fetch Infrastructure Details from SSM
        id: infra
        run: |
          echo "SUBNET_IDS=$(aws ssm get-parameter --name "/rca/infra/SUBNET_IDS" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "APP_SG_ID=$(aws ssm get-parameter --name "/rca/infra/APP_SG_ID" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "BE_TG_ARN=$(aws ssm get-parameter --name "/rca/infra/BE_TG_ARN" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "FE_TG_ARN=$(aws ssm get-parameter --name "/rca/infra/FE_TG_ARN" --query "Parameter.Value" --output text)" >> $GITHUB_ENV

      - uses: aws-actions/amazon-ecr-login@v2

      - name: Build & Push Backend
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_BACKEND_REPO }}:${{ env.IMAGE_TAG }}
          docker build -t backend ./backend
          docker tag backend:latest $IMAGE
          docker push $IMAGE

      - name: Build & Push Frontend
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_FRONTEND_REPO }}:${{ env.IMAGE_TAG }}
          docker build -t frontend ./frontend
          docker tag frontend:latest $IMAGE
          docker push $IMAGE

      - name: Register Backend Task Definition
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          REGION=${{ env.AWS_REGION }}

          SECRET_ARN="arn:aws:secretsmanager:$REGION:$ACCOUNT_ID:secret:my-backend-secrets"

          IMAGE=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/${{ env.ECR_BACKEND_REPO }}:${{ env.IMAGE_TAG }}

          cat > be-task.json <<EOF
          {
            "family": "${{ env.ECS_SERVICE_BACKEND }}",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "${{ env.ECR_BACKEND_REPO }}",
                "image": "$IMAGE",
                "cpu": 256,
                "memory": 512,
                "portMappings": [
                  { "containerPort": 8000, "hostPort": 8000, "protocol": "tcp" }
                ],
                "essential": true,
                "secrets": [
                  { "name": "DB_HOST", "valueFrom": "$SECRET_ARN:DB_HOST::" },
                  { "name": "DB_USER", "valueFrom": "$SECRET_ARN:DB_USER::" },
                  { "name": "DB_PASSWORD", "valueFrom": "$SECRET_ARN:DB_PASSWORD::" },
                  { "name": "DB_NAME", "valueFrom": "$SECRET_ARN:DB_NAME::" },
                  { "name": "DB_PORT", "valueFrom": "$SECRET_ARN:DB_PORT::" }
                ],
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/${{ env.ECS_SERVICE_BACKEND }}",
                    "awslogs-region": "$REGION",
                    "awslogs-stream-prefix": "ecs",
                    "awslogs-create-group": "true"
                  }
                }
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "arn:aws:iam::$ACCOUNT_ID:role/ecsTaskExecutionRole",
            "taskRoleArn": "arn:aws:iam::$ACCOUNT_ID:role/ecsTaskExecutionRole"
          }
          EOF
          BE_TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://be-task.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "BE_TASK_ARN=$BE_TASK_ARN" >> $GITHUB_ENV

      - name: Deploy or Create Backend Service
        run: |
          CLEAN_SUBNETS=$(echo "${{ env.SUBNET_IDS }}" | tr ' ' ',' | tr -d '\n')
          echo "FINAL SUBNETS=[${CLEAN_SUBNETS}]"

          STATUS=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE_BACKEND }} \
            --query "services[0].status" \
            --output text 2>/dev/null || echo "MISSING")

          if [ "$STATUS" = "ACTIVE" ]; then
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service ${{ env.ECS_SERVICE_BACKEND }} \
              --task-definition ${{ env.BE_TASK_ARN }} \
              --force-new-deployment
          else
            aws ecs create-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service-name ${{ env.ECS_SERVICE_BACKEND }} \
              --task-definition ${{ env.BE_TASK_ARN }} \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${CLEAN_SUBNETS}],securityGroups=[${{ env.APP_SG_ID }}],assignPublicIp=ENABLED}" \
              --load-balancers "targetGroupArn=${{ env.BE_TG_ARN }},containerName=${{ env.ECR_BACKEND_REPO }},containerPort=8000"
          fi

      - name: Register Frontend Task Definition
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          IMAGE=$ACCOUNT_ID.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_FRONTEND_REPO }}:${{ env.IMAGE_TAG }}

          cat > fe-task.json <<EOF
          {
            "family": "${{ env.ECS_SERVICE_FRONTEND }}",
            "networkMode": "awsvpc",
            "containerDefinitions": [
              {
                "name": "${{ env.ECR_FRONTEND_REPO }}",
                "image": "$IMAGE",
                "cpu": 256,
                "memory": 512,
                "portMappings": [
                  { "containerPort": 80, "hostPort": 80, "protocol": "tcp" }
                ],
                "essential": true,
                "logConfiguration": {
                  "logDriver": "awslogs",
                  "options": {
                    "awslogs-group": "/ecs/${{ env.ECS_SERVICE_FRONTEND }}",
                    "awslogs-region": "${{ env.AWS_REGION }}",
                    "awslogs-stream-prefix": "ecs",
                    "awslogs-create-group": "true"
                  }
                }
              }
            ],
            "requiresCompatibilities": ["FARGATE"],
            "cpu": "256",
            "memory": "512",
            "executionRoleArn": "arn:aws:iam::$ACCOUNT_ID:role/ecsTaskExecutionRole",
            "taskRoleArn": "arn:aws:iam::$ACCOUNT_ID:role/ecsTaskExecutionRole"
          }
          EOF
          FE_TASK_ARN=$(aws ecs register-task-definition --cli-input-json file://fe-task.json --query 'taskDefinition.taskDefinitionArn' --output text)
          echo "FE_TASK_ARN=$FE_TASK_ARN" >> $GITHUB_ENV

      - name: Deploy or Create Frontend Service
        run: |
          CLEAN_SUBNETS=$(echo "${{ env.SUBNET_IDS }}" | tr ' ' ',' | tr -d '\n')
          echo "FINAL SUBNETS=[${CLEAN_SUBNETS}]"

          STATUS=$(aws ecs describe-services \
            --cluster ${{ env.ECS_CLUSTER }} \
            --services ${{ env.ECS_SERVICE_FRONTEND }} \
            --query "services[0].status" \
            --output text 2>/dev/null || echo "MISSING")

          if [ "$STATUS" = "ACTIVE" ]; then
            aws ecs update-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service ${{ env.ECS_SERVICE_FRONTEND }} \
              --task-definition ${{ env.FE_TASK_ARN }} \
              --force-new-deployment
          else
            aws ecs create-service \
              --cluster ${{ env.ECS_CLUSTER }} \
              --service-name ${{ env.ECS_SERVICE_FRONTEND }} \
              --task-definition ${{ env.FE_TASK_ARN }} \
              --desired-count 1 \
              --launch-type FARGATE \
              --network-configuration "awsvpcConfiguration={subnets=[${CLEAN_SUBNETS}],securityGroups=[${{ env.APP_SG_ID }}],assignPublicIp=ENABLED}" \
              --load-balancers "targetGroupArn=${{ env.FE_TG_ARN }},containerName=${{ env.ECR_FRONTEND_REPO }},containerPort=80"
          fi
